# set working directory for data. Change this to your folder on your compter
workingDir <- "E:/Special/Desktop/MetMasterdata/Data"
WorkingFile <- paste(workingDir,"/MetObjects.csv",collapse = NULL, sep='')
setwd(workingDir)
#Import Met Object
MetObjects <- read.csv(file = WorkingFile)
#ClassificationCleanUpData = read.csv(file = WorkingFile2)
#List Column names in cosole
colnames(MetObjects)
View(MetObjects)
MetObjects
WorkData <- MetObjects
WorkData$Object.Mean.Date <- round((WorkData$Object.Begin.Date + WorkData$Object.End.Date)/2,0)
WorkData$Object.NewClassification <- round((WorkData$Object.Begin.Date + WorkData$Object.End.Date)/2,0)
colnames(WorkData)
View(WorkData)
options(stringsAsFactors = FALSE)
WorkData$NewClassification <- ifelse(grepl("Accessory",WorkData$Classification) == TRUE, "Accessory", NA) 		
WorkData$NewClassification <- ifelse(grepl("Aerophone",WorkData$Classification) == TRUE, "Aerophone", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Albums",WorkData$Classification) == TRUE, "Albums", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Amber",WorkData$Classification) == TRUE, "Amber", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Archery Equipment",WorkData$Classification) == TRUE, "Archery Equipment", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Architecture",WorkData$Classification) == TRUE, "Architecture", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Archives",WorkData$Classification) == TRUE, "Archives", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Armor",WorkData$Classification) == TRUE, "Armor", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Assemblages",WorkData$Classification) == TRUE, "Assemblages", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Bamboo",WorkData$Classification) == TRUE, "Bamboo", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Banners",WorkData$Classification) == TRUE, "Banners", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Bark",WorkData$Classification) == TRUE, "Bark", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Basketry",WorkData$Classification) == TRUE, "Basketry", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Beads",WorkData$Classification) == TRUE, "Beads", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Bindings",WorkData$Classification) == TRUE, "Bindings", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Blocks",WorkData$Classification) == TRUE, "Blocks", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Bone",WorkData$Classification) == TRUE, "Bone", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Books",WorkData$Classification) == TRUE, "Books", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Bronzes",WorkData$Classification) == TRUE, "Bronzes", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Calligraphy",WorkData$Classification) == TRUE, "Calligraphy", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Ceramics",WorkData$Classification) == TRUE, "Ceramics", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Chess Sets",WorkData$Classification) == TRUE, "Chess Sets", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Chordophone",WorkData$Classification) == TRUE, "Chordophone", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Clay",WorkData$Classification) == TRUE, "Clay", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Codices",WorkData$Classification) == TRUE, "Codices", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Coins",WorkData$Classification) == TRUE, "Coins", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Collages",WorkData$Classification) == TRUE, "Collages", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Costumes",WorkData$Classification) == TRUE, "Costumes", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Crèche",WorkData$Classification) == TRUE, "Crèche", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Cricket cages",WorkData$Classification) == TRUE, "Cricket cages", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Cut Paper",WorkData$Classification) == TRUE, "Cut Paper", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Cylinder seals",WorkData$Classification) == TRUE, "Cylinder seals", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Decorative arts",WorkData$Classification) == TRUE, "Decorative arts", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Documents",WorkData$Classification) == TRUE, "Documents", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Drawings",WorkData$Classification) == TRUE, "Drawings", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Electrophone",WorkData$Classification) == TRUE, "Electrophone", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Enamels",WorkData$Classification) == TRUE, "Enamels", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Enamels|Metalwork-Silver",WorkData$Classification) == TRUE, "Enamels|Metalwork-Silver", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Enamels|Miniatures",WorkData$Classification) == TRUE, "Enamels|Miniatures", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Enamels-Basse taille",WorkData$Classification) == TRUE, "Enamels-Basse taille", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Enamels-Champlevé & Cloisonné",WorkData$Classification) == TRUE, "Enamels-Champlevé & Cloisonné", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Enamels-Champlevé",WorkData$Classification) == TRUE, "Enamels-Champlevé", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Enamels-Cloisonné",WorkData$Classification) == TRUE, "Enamels-Cloisonné", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Enamels-Émail de plique",WorkData$Classification) == TRUE, "Enamels-Émail de plique", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Enamels-Painted",WorkData$Classification) == TRUE, "Enamels-Painted", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Enamels-Ronde Bosse",WorkData$Classification) == TRUE, "Enamels-Ronde Bosse", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Enamels-Surrey",WorkData$Classification) == TRUE, "Enamels-Surrey", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Enamels-Translucent",WorkData$Classification) == TRUE, "Enamels-Translucent", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Engravings",WorkData$Classification) == TRUE, "Engravings", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Ephemera",WorkData$Classification) == TRUE, "Ephemera", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Equestrian Equipment",WorkData$Classification) == TRUE, "Equestrian Equipment", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Faience",WorkData$Classification) == TRUE, "Faience", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Fans",WorkData$Classification) == TRUE, "Fans", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Feathers",WorkData$Classification) == TRUE, "Feathers", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Fencing Equipment",WorkData$Classification) == TRUE, "Fencing Equipment", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Firearms",WorkData$Classification) == TRUE, "Firearms", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Forgeries",WorkData$Classification) == TRUE, "Forgeries", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Frames",WorkData$Classification) == TRUE, "Frames", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Furniture",WorkData$Classification) == TRUE, "Furniture", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Games",WorkData$Classification) == TRUE, "Games", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Gems",WorkData$Classification) == TRUE, "Gems", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Gesso",WorkData$Classification) == TRUE, "Gesso", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Glass",WorkData$Classification) == TRUE, "Glass", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Gold and Silver",WorkData$Classification) == TRUE, "Gold and Silver", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Gold",WorkData$Classification) == TRUE, "Gold", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Gourd",WorkData$Classification) == TRUE, "Gourd", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Hardstone",WorkData$Classification) == TRUE, "Hardstone", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Helmets",WorkData$Classification) == TRUE, "Helmets", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Hide",WorkData$Classification) == TRUE, "Hide", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Horn",WorkData$Classification) == TRUE, "Horn", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Horology",WorkData$Classification) == TRUE, "Horology", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Idiophone",WorkData$Classification) == TRUE, "Idiophone", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Ink",WorkData$Classification) == TRUE, "Ink", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Inr?",WorkData$Classification) == TRUE, "Inr?", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Installations",WorkData$Classification) == TRUE, "Installations", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Ivory",WorkData$Classification) == TRUE, "Ivory", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Jade",WorkData$Classification) == TRUE, "Jade", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Jewelry",WorkData$Classification) == TRUE, "Jewelry", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Lacquer",WorkData$Classification) == TRUE, "Lacquer", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Lapidary Work",WorkData$Classification) == TRUE, "Lapidary Work", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Leather",WorkData$Classification) == TRUE, "Leather", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Letters",WorkData$Classification) == TRUE, "Letters", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Lighting",WorkData$Classification) == TRUE, "Lighting", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Machines & Appliances",WorkData$Classification) == TRUE, "Machines & Appliances", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Main Dress",WorkData$Classification) == TRUE, "Main Dress", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Manuscripts",WorkData$Classification) == TRUE, "Manuscripts", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Masks",WorkData$Classification) == TRUE, "Masks", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Medals",WorkData$Classification) == TRUE, "Medals", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Membranophone",WorkData$Classification) == TRUE, "Membranophone", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Metal",WorkData$Classification) == TRUE, "Metal", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Miniatures",WorkData$Classification) == TRUE, "Miniatures", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Mirrors",WorkData$Classification) == TRUE, "Mirrors", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Miscellaneous",WorkData$Classification) == TRUE, "Miscellaneous", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Models",WorkData$Classification) == TRUE, "Models", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Mosaics",WorkData$Classification) == TRUE, "Mosaics", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Musical instruments",WorkData$Classification) == TRUE, "Musical instruments", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("NA",WorkData$Classification) == TRUE, "NA", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Natural Substances",WorkData$Classification) == TRUE, "Natural Substances", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Negatives",WorkData$Classification) == TRUE, "Negatives", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Netsuke",WorkData$Classification) == TRUE, "Netsuke", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Night and Dressing Wear",WorkData$Classification) == TRUE, "Night and Dressing Wear", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Ojime",WorkData$Classification) == TRUE, "Ojime", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Outerwear",WorkData$Classification) == TRUE, "Outerwear", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Paintings",WorkData$Classification) == TRUE, "Paintings", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Paper",WorkData$Classification) == TRUE, "Paper", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Papier Mâché",WorkData$Classification) == TRUE, "Papier Mâché", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Papyrus",WorkData$Classification) == TRUE, "Papyrus", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Parchment",WorkData$Classification) == TRUE, "Parchment", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Pastels & Oil Sketches on Paper",WorkData$Classification) == TRUE, "Pastels & Oil Sketches on Paper", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Periodicals",WorkData$Classification) == TRUE, "Periodicals", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Photographic Equipment",WorkData$Classification) == TRUE, "Photographic Equipment", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Photographs",WorkData$Classification) == TRUE, "Photographs", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Plaquettes",WorkData$Classification) == TRUE, "Plaquettes", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Plaster",WorkData$Classification) == TRUE, "Plaster", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Plastic",WorkData$Classification) == TRUE, "Plastic", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Plates",WorkData$Classification) == TRUE, "Plates", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Portfolios",WorkData$Classification) == TRUE, "Portfolios", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Portraits",WorkData$Classification) == TRUE, "Portraits", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Postage Stamps|Prints",WorkData$Classification) == TRUE, "Postage Stamps|Prints", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Postcards",WorkData$Classification) == TRUE, "Postcards", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Posters",WorkData$Classification) == TRUE, "Posters", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Prints",WorkData$Classification) == TRUE, "Prints", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Reproductions",WorkData$Classification) == TRUE, "Reproductions", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Rubbing",WorkData$Classification) == TRUE, "Rubbing", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Saddle Plates",WorkData$Classification) == TRUE, "Saddle Plates", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Scientific Instruments",WorkData$Classification) == TRUE, "Scientific Instruments", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Screens",WorkData$Classification) == TRUE, "Screens", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Sculpture",WorkData$Classification) == TRUE, "Sculpture", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Seals",WorkData$Classification) == TRUE, "Seals", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Sharkskin",WorkData$Classification) == TRUE, "Sharkskin", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Shell",WorkData$Classification) == TRUE, "Shell", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Shields",WorkData$Classification) == TRUE, "Shields", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Silver",WorkData$Classification) == TRUE, "Silver", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Sketchbooks",WorkData$Classification) == TRUE, "Sketchbooks", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Smoking Equipment",WorkData$Classification) == TRUE, "Smoking Equipment", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Snuff Bottles",WorkData$Classification) == TRUE, "Snuff Bottles", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Snuffboxes",WorkData$Classification) == TRUE, "Snuffboxes", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Soapstone",WorkData$Classification) == TRUE, "Soapstone", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Sound Recordings",WorkData$Classification) == TRUE, "Sound Recordings", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Steatites",WorkData$Classification) == TRUE, "Steatites", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Stencils",WorkData$Classification) == TRUE, "Stencils", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Stone",WorkData$Classification) == TRUE, "Stone", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Stucco",WorkData$Classification) == TRUE, "Stucco", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Supplies",WorkData$Classification) == TRUE, "Supplies", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Surcoat",WorkData$Classification) == TRUE, "Surcoat", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Sword Furniture",WorkData$Classification) == TRUE, "Sword Furniture", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Terracottas",WorkData$Classification) == TRUE, "Terracottas", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Textiles",WorkData$Classification) == TRUE, "Textiles", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Textiles-Woven-Brocade",WorkData$Classification) == TRUE, "Textiles-Woven-Brocade", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Tobacco Pouches",WorkData$Classification) == TRUE, "Tobacco Pouches", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Tomb Pottery",WorkData$Classification) == TRUE, "Tomb Pottery", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Tools",WorkData$Classification) == TRUE, "Tools", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Transparencies",WorkData$Classification) == TRUE, "Transparencies", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Underwear",WorkData$Classification) == TRUE, "Underwear", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Variable Media",WorkData$Classification) == TRUE, "Variable Media", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Vases",WorkData$Classification) == TRUE, "Vases", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Wallpaper",WorkData$Classification) == TRUE, "Wallpaper", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Wax-Sculpture",WorkData$Classification) == TRUE, "Wax-Sculpture", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Weapons",WorkData$Classification) == TRUE, "Weapons", WorkData$NewClassification) 		
WorkData$NewClassification <- ifelse(grepl("Wood",WorkData$Classification) == TRUE, "Wood", WorkData$NewClassification)
write.csv(MetObjectsDraft <- WorkData, file = "MetObjectsFinal.csv")
