#install.packages('tidyverse') #uncomment to install packages
library('tidyverse')
workingDir <- "E:/Special/Desktop/MetMasterdata/Data"
WorkingFile <- paste(workingDir,"/MetObjects.csv",collapse = NULL, sep='')
setwd(workingDir)
#Import Met Object
MetObjects <- read.csv(file = WorkingFile)
# set working directory for data. Change this to your folder on your compter
#workingDir <- "C:\\Users\\lynes\\Desktop\\QNT745_GroupProject"
#WorkingFile <- paste(workingDir,"/MetObjects.csv",collapse = NULL, sep='')
#setwd("C:\\Users\\lynes\\Desktop\\QNT745_GroupProject")

#Import Met Object and replace missing values with NA
#MetObjects <- read.csv(file = WorkingFile, sep = ',', na.strings="")

#List Column names in cosole
colnames(MetObjects)
View(MetObjects)

#Limit dataset to chosen variables and view new dataset
WorkData <- MetObjects[c('Object.Name','Title','Is.Public.Domain','Department','Object.Date','Object.Begin.Date','Object.End.Date','Classification','Medium')]
View(WorkData)

#Run as factor
options(stringsAsFactors = FALSE)

#Department: Costume Institute - Transform NAs in $Classification - Accessories
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("accessory",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Accessory",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Accessories",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Accessory set",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Purse",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("purse",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Tote",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("bag",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Bag",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Reticule",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Chatelaine",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Satchel",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Clutch",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("clutch",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Carpetbag",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Pouch",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Briefcase",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Muff",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Garters",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Shoe",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("shoes",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Sandals",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Sandal",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Pumps",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("pumps",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Boots",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("boots",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Clogs",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Loafers",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Mules",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Boots",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Slippers",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("slippers",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Sneakers",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Espadrilles",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Crakows",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Chopines",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Moccasins",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Oxfords",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Shoe Buckles",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Shoe Clips",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Shoe Heels",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Shoe Trees",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Collar",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("collar",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Neckpiece",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Cuffs",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Belt",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("belt",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Belt Buckle",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Suspenders",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Ribbon",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Sash",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("sash",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Comb",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("comb",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Necktie",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Jabot",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Neckcloth",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Bow tie",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Neckerchief",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Bertha",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Stock",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Bow",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Hairpin",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Headband",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Barrette",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Barbe",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Aigrette",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Tiara",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Hat",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("hat",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Hatbox",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Cap",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("cap",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Mobcap",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Snood",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Lappet",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Bonnet",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("bonnet",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Sunbonnet",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Headdress",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("headdress",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Headpiece",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Calash",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Tricorne",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Bicorne",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Tam-o'-shanter",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Turban",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Headscarf",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Wedding Crown",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Coif",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Homburg",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Boater",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Cloche",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Toque",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Capote",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Fedora",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Beret",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("pillbox",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Derby",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Head Protector",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Coronet",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Beret",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Jewelry",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("jewelry",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Jewelry Set",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Necklace",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Pendant",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Choker",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Bracelet",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("bracelet",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Wristlet",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("earrings",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Earrings",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Pin",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Stickpin",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Hatpin",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Brooch",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Clip",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Ring",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Gloves",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("gloves",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Mitts",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Mittens",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Gauntlets",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Fan",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("mittens",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Case",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Cigarette Holder",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Compact",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Sunglasses",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Eyeglasses",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("glasses",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Spy-Glass",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Spectacles",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Lorgnette",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Monocle",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Pince-Nez",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Goggles",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("goggles",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Parasol",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Umbrella",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Cosmetics",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Hair Accessory",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Button",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Busk",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Boa",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Kit",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Watch",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Aiguillette",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Wig",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Epaulets",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Spurs",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Feather",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Bouquet Holder",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Cane",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Sautoir",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Fan",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("fan",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Walking stick",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Walking Stick",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Buckle",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Armlet",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Dress form",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Mannequin",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Brush",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Rubbers",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Seal",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Hairband",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Fob",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Riding Crop",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Cuff Links",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Stud",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Bar Pin",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Bar pin",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Phallocrypt",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Equipment",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Pattens",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Galoshes",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("ornament",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Ornament",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Pipe",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Sword",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Mask",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Helmet",WorkData$Object.Name)] <- "Accessories"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("MinaudiÃ¨re",WorkData$Object.Name)] <- "Accessories"

#Department: Costume Institute - Transform NAs in $Classification - Textiles (natural fibers)
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("silk",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Silk",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("SIlk",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("cotton",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Cotton",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Linen",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("linen",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("wool",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Wool",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("cashmere",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("alpaca",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("mohair",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("fur",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Fur",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("mink",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("ermine",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("angora",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("suede",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("shearling",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("hemp",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("flax",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("mull",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("lambswool",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("snakeskin",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("leather",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Leather",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("paper",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Paper",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("metal",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("piÃ±a",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("fiber",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("camel",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("sable",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("straw",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("chamois",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("calfskin",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("horsehair",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("goatskin",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("sheepskin",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("skin",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("jet",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("feather",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("feathers",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("raffia",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("aloe",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Orion",WorkData$Medium)] <- "Textiles"

#Department: Costume Institute - Transform NAs in $Classification - Textiles (synthetic fibers)
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("synthetics",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("synthetic",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Synthetic",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Synethetic",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("ultrasuede",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Polyester",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("polyester",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Rayon",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("rayon",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("viscose",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("nylon",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Nylon",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("elastic",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("spandex",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("lurex",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Lurex",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Lycra",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("lycra",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("velvet",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("sequins",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("polyethylene",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("estron",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("jersey",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("no medium available",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("no medium available",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("medium not availalble",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("plastic",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("acetate",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("vinyl",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Acrylic",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("acrylic",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Metallic",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("wire",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("dacron",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("lace",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("beads",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("crystal",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("crystals",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Lyocell",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Kaycel",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Tyvek",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("resin",WorkData$Medium)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("polyurethane",WorkData$Medium)] <- "Textiles"

#Department: Costume Institute - Transform NAs in $Classification - Textiles (by garment type)
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Corset",WorkData$Object.Name)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("T-shirt",WorkData$Object.Name)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Sweater",WorkData$Object.Name)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("gown",WorkData$Object.Name)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Dress",WorkData$Object.Name)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("dress",WorkData$Object.Name)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Suit",WorkData$Object.Name)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Underwear",WorkData$Object.Name)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Briefs",WorkData$Object.Name)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Jacket",WorkData$Object.Name)] <- "Textiles"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Ensemble",WorkData$Object.Name)] <- "Textiles"

#Department: Costume Institute - Transform NAs in $Classification - Photographs
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Image",WorkData$Object.Name)] <- "Photographs"
WorkData$Classification[is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department)&grepl("Photograph",WorkData$Object.Name)] <- "Photographs"

#Department: The Libraries - Transform NAs in $Classification - Books
WorkData$Classification[is.na(WorkData$Classification)&grepl("The Libraries",WorkData$Department)] <- "Books and Serials"

#analyze missing values
sum(is.na(WorkData$Classification)&grepl("Costume Institute",WorkData$Department))
sum(is.na(WorkData$Classification)&grepl("The Libraries",WorkData$Department))
map(WorkData, ~sum(is.na(.)))
View(WorkData)

write.csv(MetObjectsDraft <- WorkData, file = "MetObjectsPrepFinal.csv")
